APP_NAME=Lumen
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_URL=http://localhost
APP_TIMEZONE=UTC

LOG_CHANNEL=stack
LOG_SLACK_WEBHOOK_URL=

DB_CONNECTION=pgsql
DB_HOST=127.0.0.1
DB_PORT=5415
DB_DATABASE=swift_parser
DB_USERNAME=novaji
DB_PASSWORD=S3cret

CACHE_DRIVER=file
QUEUE_CONNECTION=sync

FTP_USER=cidergs
FTP_PASSWORD=EnochEmmanuel123
FTP_HOST=ftp.cluster051.hosting.ovh.net
FTP_PORT=21
FTP_DIR="swift"
PROCESSED_DIR=PROCESSED
EXPORT_FILE_PREFIX=SwiftParser_Export
APP_STORAGE_EXPORT_DIR=exports
STORAGE_TYPE=local
STORAGE_DIR=storage/app

MAIL_MAILER=smtp
MAIL_HOST=smtp.mail.ovh.ca
MAIL_PORT=465
MAIL_USERNAME=tech-support@cidergloballtd.com
MAIL_PASSWORD=Shadow123_
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=tech-support@cidergloballtd.com
MAIL_FROM_NAME="Technical Support"
PASSWORD_RESET_SUBJECT="Swift Parser - Password Reset"
